title: Robert Keyes | Professional Portfolio
url: "https://cmdawesome.github.io"
baseurl: ""
techfolio-theme: default.css
rouge-theme: github.css
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
strict_front_matter: true
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - projects
  - essays
include:
  - .nojekyll
  - _data
plugins:
  - jekyll-gist
